export default function TermsPage() {
  return (
    <div className="p-6 sm:p-8 max-w-[900px] flex flex-col gap-6">
      <h1 className="text-[40px] sm:text-[56px] font-black tracking-[-2px] uppercase text-[#e2e2e2]" style={{ fontFamily: "'Epilogue', sans-serif" }}>
        Terms of Service
      </h1>
      <div className="bg-[#1b1b1b] p-6 border border-[rgba(67,70,85,0.2)] space-y-4">
        <p className="text-[13px] text-[#c3c6d7] leading-6" style={{ fontFamily: "'Inter', sans-serif" }}>
          By accessing and using Stumped AI you agree to comply with these terms. The platform is provided for informational and analytical purposes only. All data, predictions, and simulations are generated by AI models and should not be considered absolute guarantees of match outcomes.
        </p>
        <p className="text-[13px] text-[#c3c6d7] leading-6" style={{ fontFamily: "'Inter', sans-serif" }}>
          Users are responsible for how they apply insights from the platform. Stumped AI reserves the right to modify, suspend, or discontinue any part of the service at any time. Unauthorized reproduction, redistribution, or commercial use of our data and analytics without written consent is strictly prohibited.
        </p>
        <p className="text-[13px] text-[#c3c6d7] leading-6" style={{ fontFamily: "'Inter', sans-serif" }}>
          For full terms, data handling policies, and dispute resolution procedures, contact our support team.
        </p>
      </div>
    </div>
  );
}
